In [1]:
pip install -q -U torch==2.0.0

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install -q -U accelerate==0.23.0 peft==0.5.0 bitsandbytes==0.41.1 transformers==4.31 trl==0.7.2 torch==2.0.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kaggle-environments 1.14.3 requires transformers>=4.33.1, but you have transformers 4.31.0 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [3]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import bitsandbytes as bnb
import torch
import torch.nn as nn
import transformers
from datasets import Dataset
from peft import LoraConfig, PeftConfig
from trl import SFTTrainer
from transformers import (AutoModelForCausalLM, 
                          AutoTokenizer, 
                          BitsAndBytesConfig, 
                          TrainingArguments, 
                          pipeline, 
                          logging)
from sklearn.metrics import (accuracy_score, 
                             classification_report, 
                             confusion_matrix)
from sklearn.model_selection import train_test_split

In [6]:
print(f"pytorch version {torch.__version__}")

pytorch version 2.0.0


In [7]:
from datasets import load_dataset

dataset = load_dataset("uitnlp/vietnamese_students_feedback")
dataset = dataset.rename_column("sentence", 'text')
dataset = dataset.rename_column("sentiment", 'label')
dataset = dataset.remove_columns("topic")
dataset

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Dataset vietnamese_students_feedback downloaded and prepared to /root/.cache/huggingface/datasets/uitnlp___vietnamese_students_feedback/default/1.0.0/b01aa0fea00f1179ef9c093babb5e91f44bc60f19ded600754a08e018503e40f. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 11426
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 1583
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 3166
    })
})

In [8]:
import pandas as pd
from datasets import Dataset
synonym_sentiment = pd.read_csv("/kaggle/input/synonym-sentiment-2/data_aug_synonym.csv")
synonym_sentiment.drop(columns=['Unnamed: 0'], inplace=True)
features = synonym_sentiment.to_dict('list')  # Convert DataFrame to a dictionary of lists
train_dataset = Dataset.from_dict(features)
dataset['train'] = train_dataset

In [9]:
def generate_prompt(data_point):
    return f"""
            Analyze the sentiment of the news headline enclosed in square brackets, 
            determine if it is positive, neutral, or negative, and return the answer as 
            the corresponding sentiment label "positive" or "neutral" or "negative".

            [{data_point["text"]}] = {data_point["sentiment"]}
            """.strip()

def generate_test_prompt(data_point):
    return f"""
            Analyze the sentiment of the news headline enclosed in square brackets, 
            determine if it is positive, neutral, or negative, and return the answer as 
            the corresponding sentiment label "positive" or "neutral" or "negative".

            [{data_point["text"]}] = """.strip()

def quantile(score):
    if score <1: return "negative"
    elif score == 1:return "neutral"
    else: return "positive"

In [10]:
from datasets import Dataset
train_dataset = pd.DataFrame(dataset['train'])
train_dataset['sentiment'] = train_dataset['label'].apply(quantile)
train_dataset['text'] = train_dataset.apply(generate_prompt, axis=1)
train_data = Dataset.from_pandas(train_dataset)
eval_dataset = pd.DataFrame(dataset['validation'])
eval_dataset['sentiment'] = eval_dataset['label'].apply(quantile)
eval_dataset['text'] = eval_dataset.apply(generate_prompt, axis=1)
eval_data = Dataset.from_pandas(eval_dataset)
test_dataset = pd.DataFrame(dataset['test'])
test_dataset['sentiment'] = test_dataset['label'].apply(quantile)
test_dataset['text'] = test_dataset.apply(generate_test_prompt, axis=1)
test_data = Dataset.from_pandas(test_dataset)

In [11]:
def evaluate(y_true, y_pred):
    labels = ['positive', 'neutral', 'negative']
    mapping = {'positive': 2, 'neutral': 1, 'none':1, 'negative': 0}
    def map_func(x):
        return mapping.get(x, 1)
    
    y_true = np.vectorize(map_func)(y_true)
    y_pred = np.vectorize(map_func)(y_pred)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_true=y_true, y_pred=y_pred)
    print(f'Accuracy: {accuracy:.3f}')
    
    # Generate accuracy report
    unique_labels = set(y_true)  # Get unique labels
    
    for label in unique_labels:
        label_indices = [i for i in range(len(y_true)) 
                         if y_true[i] == label]
        label_y_true = [y_true[i] for i in label_indices]
        label_y_pred = [y_pred[i] for i in label_indices]
        accuracy = accuracy_score(label_y_true, label_y_pred)
        print(f'Accuracy for label {label}: {accuracy:.3f}')
        
    # Generate classification report
    class_report = classification_report(y_true=y_true, y_pred=y_pred)
    print('\nClassification Report:')
    print(class_report)
    
    # Generate confusion matrix
    conf_matrix = confusion_matrix(y_true=y_true, y_pred=y_pred, labels=[0, 1, 2])
    print('\nConfusion Matrix:')
    print(conf_matrix)

In [12]:
!pip install huggingface_hub

In [13]:
import huggingface_hub
huggingface_hub.login(token='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')

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [14]:
model_name = "meta-llama/Llama-2-7b-hf"

compute_dtype = getattr(torch, "float16")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=False,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    quantization_config=bnb_config, 
    token='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',
)

model.config.use_cache = False
model.config.pretraining_tp = 1

tokenizer = AutoTokenizer.from_pretrained(model_name, 
                                          trust_remote_code=True,
                                         )
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

In [15]:
def predict(X_test, model, tokenizer):
    y_pred = []
    for i in tqdm(range(len(X_test))):
        prompt = X_test["text"][i]
        pipe = pipeline(task="text-generation", 
                        model=model, 
                        tokenizer=tokenizer, 
                        max_new_tokens = 1, 
                        temperature = 0.0,
                       )
        result = pipe(prompt)
        answer = result[0]['generated_text'].split("=")[-1]
        if "positive" in answer:
            y_pred.append("positive")
        elif "negative" in answer:
            y_pred.append("negative")
        elif "neutral" in answer:
            y_pred.append("neutral")
        else:
            y_pred.append("none")
    return y_pred

In [16]:
y_pred = predict(test_data, model, tokenizer)

  0%|          | 0/3166 [00:00<?, ?it/s]Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
100%|██████████| 3166/3166 [20:04<00:00,  2.63it/s]


In [17]:
y_true = test_data['sentiment']
evaluate(y_true, y_pred)

Accuracy: 0.180
Accuracy for label 0: 0.006
Accuracy for label 1: 0.928
Accuracy for label 2: 0.256

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.01      0.01      1409
           1       0.06      0.93      0.11       167
           2       0.90      0.26      0.40      1590

    accuracy                           0.18      3166
   macro avg       0.62      0.40      0.17      3166
weighted avg       0.85      0.18      0.21      3166


Confusion Matrix:
[[   8 1368   33]
 [   0  155   12]
 [   1 1182  407]]


In [18]:
import wandb
import os
os.environ['WANDB_PROJECT'] = "experiment"
os.environ['WANDB_LOG_MODEL'] = "true"

In [19]:
import re
run_name=re.sub(r'/', "-", model_name) + "_sentiment_mining_LLM_" + "14"

In [20]:
peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    bias="none",
    task_type="CAUSAL_LM",
)

training_arguments = TrainingArguments(
    output_dir="logs",
    num_train_epochs=3,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8, # 4
    optim="paged_adamw_32bit",
    save_steps=0,
    logging_steps=50,
    learning_rate=2e-4,
    weight_decay=0.001,
    fp16=True,
    bf16=False,
    max_grad_norm=0.3,
    max_steps=-1,
    warmup_ratio=0.03,
    group_by_length=True,
    lr_scheduler_type="cosine",
    report_to="wandb",
    run_name=run_name,
    evaluation_strategy="epoch"
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_data,
    eval_dataset=eval_data,
    peft_config=peft_config,
    dataset_text_field="text",
    tokenizer=tokenizer,
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

  0%|          | 0/15 [00:00<?, ?ba/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

In [21]:
# Train model
wandb.login(key="e4c568fdefe63f6dcc6f88155c670e1d058abbf8")
trainer.train()

# Save trained model
trainer.model.save_pretrained("trained-model")

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: huysntq (sfdsafa). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20231231_024414-qabeve7o
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run meta-llama-Llama-2-7b-hf_sentiment_mining_LLM_14
wandb: ⭐️ View project at https://wandb.ai/sfdsafa/experiment
wandb: 🚀 View run at https://wandb.ai/sfdsafa/experiment/runs/qabeve7o
You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode t

In [22]:
trainer.evaluate()

{'eval_loss': 0.39246878027915955,
 'eval_runtime': 499.0162,
 'eval_samples_per_second': 3.172,
 'eval_steps_per_second': 0.397,
 'epoch': 3.0}

In [23]:
y_pred = predict(test_data, model, tokenizer)
y_true = test_data['sentiment']
evaluate(y_true, y_pred)

100%|██████████| 3166/3166 [22:02<00:00,  2.39it/s]

Accuracy: 0.931
Accuracy for label 0: 0.953
Accuracy for label 1: 0.593
Accuracy for label 2: 0.947

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1409
           1       0.54      0.59      0.57       167
           2       0.96      0.95      0.95      1590

    accuracy                           0.93      3166
   macro avg       0.82      0.83      0.82      3166
weighted avg       0.93      0.93      0.93      3166


Confusion Matrix:
[[1343   40   26]
 [  26   99   42]
 [  40   44 1506]]
